// Reads img/*.{png,jpg} and emits src/generated/assets.ts with base64 data URIs.
// Main background is resized + recompressed to keep bundle size small.
import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const imgDir = path.join(root, 'img');
const outDir = path.join(root, 'src', 'generated');
const outFile = path.join(outDir, 'assets.ts');

const MAIN_WIDTH = 900; // px (unused; SVG passed through)
const ICON_WIDTH = 128; // px

const CONST_NAMES = {
    'main.svg': 'MAIN_BG',
    'alarm.png': 'ICON_ALARM',
    'compressor.png': 'ICON_COMPRESSOR',
    'cool.png': 'ICON_COOL',
    'defrost.png': 'ICON_DEFROST',
    'heat.png': 'ICON_HEAT',
    'produce.png': 'ICON_PRODUCE',
    'stop.png': 'ICON_STOP',
    'user.png': 'ICON_USER',
    'week.png': 'ICON_WEEK',
};

async function processImage(file) {
    const filePath = path.join(imgDir, file);
    const ext = path.extname(file).toLowerCase();
    if (ext === '.svg') {
        const buffer = await fs.readFile(filePath);
        return { mime: 'image/svg+xml', b64: buffer.toString('base64'), bytes: buffer.length };
    }
    const pipeline = sharp(filePath).resize({ width: ICON_WIDTH, withoutEnlargement: true });
    let buffer;
    let mime;
    if (ext === '.png') {
        buffer = await pipeline.png({ compressionLevel: 9, palette: true }).toBuffer();
        mime = 'image/png';
    } else {
        buffer = await pipeline.jpeg({ quality: 82 }).toBuffer();
        mime = 'image/jpeg';
    }
    return { mime, b64: buffer.toString('base64'), bytes: buffer.length };
}

async function main() {
    await fs.mkdir(outDir, { recursive: true });
    const files = (await fs.readdir(imgDir)).filter((f) => CONST_NAMES[f]);
    files.sort();
    const lines = [
        '// AUTO-GENERATED by scripts/build-assets.mjs. Do not edit.',
        '/* eslint-disable */',
        '',
    ];
    let total = 0;
    for (const file of files) {
        const { mime, b64, bytes } = await processImage(file);
        total += bytes;
        const name = CONST_NAMES[file];
        lines.push(`// ${file} - ${(bytes / 1024).toFixed(1)} KB`);
        lines.push(`export const ${name} = 'data:${mime};base64,${b64}';`);
        lines.push('');
    }
    lines.push(`// Total embedded asset size: ${(total / 1024).toFixed(1)} KB`);
    lines.push('');
    await fs.writeFile(outFile, lines.join('\n'), 'utf8');
    console.log(`[build-assets] wrote ${outFile} (${(total / 1024).toFixed(1)} KB embedded)`);
}

main().catch((err) => {
    console.error(err);
    process.exit(1);
});
